### ISSUE TITLE
Borosilicate glass turns to total transparent

### ISSUE THREAD

**Issue by Eticeweng** [MCTian-mi/Zederrian-Technology-GT5U#2]
Borosilicate glass(and its variety) turns to total transparent on game starts, only restored to normal after re-apply resourcepacks in game.
Modpack: GTNH 2.5.1@Java8
Optifine installed
![image](https://github.com/MCTian-mi/Zederrian-Technology-GT5U/assets/43090280/674b2010-b739-4b4e-a1f8-5256f4265369)

**Comment by Eticeweng** [comment]
update
switch to angelica still not fix the problem, and the transparent glass persist even after re-apply the resourcepacks.
but removing `\assets\bartworks\textures\blocks\connectedTex` in the unzip resourcepacks fix the problem, allowing the block glass able to render, but also returned to default look from BWs.

**Comment by Flanisch** [comment]
I believe this is not a resource pack issue, but a Bartworks issue itself. The rendering code for bartworks' glass is more than scuffed. It might be better to open an issue there.

**Comment by Eticeweng** [comment]
thanks for the reply, the workaround above is good enough for me now, but i will keep trying to get help from somewhere else, too much rendering related mod in this modpack.
